language: go

go:
  # must be quoted in order to work correctly
  - "1.10.x"
  - master

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - make clean
  - make build
  # validate for correct generation
  - make generate 

after_success:
  # Report test cover status
  - bash <(curl -s https://codecov.io/bash) 